### ISSUE TITLE
Błąd z uruchamianiem collectstatic w dockerfile na windowsie

### ISSUE THREAD

**Issue by bafaurazan** [knmlprz/ChatKNML#100]
![image](https://github.com/knmlprz/ChatKNML/assets/146839542/f262d07a-5ef4-4950-b0a0-34276d6ebb0f)
![image](https://github.com/knmlprz/ChatKNML/assets/146839542/e56b88da-0881-4df2-95d1-b02bfd8c65bb)

**Comment by pgronkievitz** [comment]
https://github.com/knmlprz/ChatKNML/pull/97/files#r1501788326
