### ISSUE TITLE
Sposób zapamiętywania tego co podał użytkownik

### ISSUE THREAD

**Issue by TheJimmyNowak** [knmlprz/ChatKNML#21]
## Jaki jest cel tego tego zadania
Dodanie prostej pamięci do chatbota.

## Jak wygląda rozwiązanie?
Gdy ktoś napisze do bota, to bot sam pobierze kilka ostatnich wiadomości z kanału.

**Na ten moment nie robimy z nimi niczego, tylko je pobieramy.**

**Comment by finloop** [comment]
@TheJimmyNowak Proponuję zmienić opis tego zadania na coś bardziej konkretnego. 

Tytuł: Dodanie prostej pamięci do Chatbota

## Jaki jest cel tego tego zadania

Dodanie prostej pamięci do chatbota.

## Jak wygląda rozwiązanie?

Gdy ktoś napisze do bota, to bot sam pobierze kilka ostatnich wiadomości z kanału. 

Na ten moment nie robimy z nimi niczego, tylko je pobieramy.

**Comment by TheJimmyNowak** [comment]
Lgtm. Zostawię starą treść jako archiwum
