### ISSUE TITLE
Recursive URL

### ISSUE THREAD

**Issue by finloop** [knmlprz/ChatKNML#22]
Sprawdzenie jak działa Langchain Recursive URL https://python.langchain.com/docs/integrations/document_loaders/recursive_url i ocenienie czy jest przydatny.

**Comment by bisd98** [comment]
Cześć zespół! Chciałem się z Wami podzielić moimi odkryciami dotyczącymi metody `RecursiveUrlLoader` z modułu `langchain`. To narzędzie jest naprawdę skuteczne i pozwala na efektywne pozyskiwanie kodu źródłowego witryn internetowych, wystarczy tylko podać adres URL!

🌐 Jednym z kluczowych punktów tej metody jest możliwość definiowania głębokości eksploracji. Dzięki argumentowi `max_depth` mamy pełną kontrolę nad zakresem, który chcemy pobrać, zaczynając od katalogu wskazanego w URL. To oznacza, że możemy zescrapować każdą stronę, która znajduje się w zasięgu wzroku metody, a może widzieć dalej niż Oko Saurona (mam na myśli to oko z Władcy Pierścieni).

🕵️‍♂️ Niezwykle istotnym elementem jest także argument `extractor`. Pozwala on spersonalizować sposób przetwarzania kodu źródłowego. Dzięki niemu możemy dostosować funkcję, która przekształci kod źródłowy na metadane oraz tekst, który jest dla nas najważniejszy!

🎓 Ostatnio przetestowałem to narzędzie na stronie politechniki i wyniki są imponujące! Uzyskałem pełną gamę danych dostępnych na stronie, bez konieczności wielokrotnego przeglądania kolejnych podstron. To idealne rozwiązanie dla tych, którzy chcą szybko i efektywnie pozyskiwać informacje z różnych źródeł.

🚨 **Podsumowując:**
- `RecursiveUrlLoader` to przydatne narzędzie do szybkiego pozyskiwania kodu źródłowego z witryn internetowych.
- Dzięki dostępnym argumentom, takim jak `max_depth` i `extractor`, możemy dostosować proces do naszych indywidualnych potrzeb.
- Idealne do scrapowania danych z różnych źródeł, w tym przypadku ze strony Politechniki.

❗Kwestie, które należy poruszyć w ramach pracy z powyższym narzędziem:
- Należy ustalić taktykę pozwalającą na scrapowanie wszystkich adresów, ze względu na dosyć egzotyczne rozmieszczenie poszczególnych stron (startując z jednego adresu URL można nie pokryć wszystkich adresów).
- Należy doprecyzować funkcję do przetwarzania kodu źródłowego, co już za niedługo poruszę w [tym wątku](https://github.com/knmlprz/ChatKNML/issues/32#issue-2006974179).

**Comment by TheJimmyNowak** [comment]
Zajebisty opis 😉 @finloop ucz się od kolegi

Prosiłbym jeszcze o link do notebooka, żebyśmy zobaczyli jakiś kod (np. to, co pokazywałeś ostatnio na kole)

**Comment by bisd98** [comment]
@TheJimmyNowak jest link 🫡
