### ISSUE TITLE
Źródło danych: strony politechniki rzeszowskiej

### ISSUE THREAD

**Issue by finloop** [knmlprz/ChatKNML#32]
Hej! Jeśli zapoznaliście się już z [taskiem, który dotyczy RecursiveUrlLoader](https://github.com/knmlprz/ChatKNML/issues/22), to wiecie, że zaistniała potrzeba użycia narzędzia do wydobycia istotnych fragmentów z zescrapowanych danych.

🤔 Głównym problemem, który pojawiał się przy pobieraniu danych ze stron był zalew niestotnych tekstów wywodzących się z nagłówków, paneli i stopek. Taka struktura sprawiała, że:
- nasze dane były zaśmiecone,
- wektory reprezentujące dane wartościowe, zmieszane ze śmieciowymi były rozmyte,
- dzielenie danych ze strony na mniejsze chunki było utrudnione,
- ilość 		białych znaków 			była	irytująca.

💡 Pierwszym podejściem do rozwiązania pomysłu było wydobycie poszczególnych sekcji strony za pomocą twardo sprecyzowanego taga, np.: <main>...</main>. Ze względu na różnorodne struktury stron, z których chcemy wydobyć dane, ten pomysł okazał się mało elastyczny.

👏 Świetne rozwiązanie zaproponował @finloop, który korzysta w swojej przeglądarce z narzędzi wydobywających istotne treści z odwiedzanych stron. Można to nazwać swego rodzaju adblockiem, który chroni użytkownika przed oczopląsem wywołanym panelem na panelu i czterema stopkami.

🕵️‍♂️ Po niewielkim researchu udało się znaleźć narzędzie, które spełnia potrzebę wydobycia istotnych fragmentów strony, a także posiada ciekawe dodatki. Owym narzędziem jest [Newspaper](https://github.com/codelucas/newspaper), który oprócz wydobycia interesującego nas kawałka danych tekstowych potrafi także streszczać zawartość strony oraz określać keywordy na podstawie zawartości.

🗒 [Link do notatnika w Google Colab](https://colab.research.google.com/drive/1xQ8-HHTiY8CHfV4f2hIUskv0P9ymUCpn?usp=sharing), w którym prezentuję praktyczne zastosowanie Newspaper.

**Comment by bisd98** [comment]
Update o link do GC notebook 😎

**Comment by TheJimmyNowak** [comment]
LGTM
