### ISSUE TITLE
Przygotowania do grudniowego spotkania

### ISSUE THREAD

**Issue by finloop** [knmlprz/ChatKNML#36]
## Jaki jest cel tego tego zadania

Dwiedzieć się ile czasu mamy na grudniowym spotkaniu koła na przedstawienie wszystkich prezentacji.

## TODO:

- [x] Zapytać się damiana

**Comment by TheJimmyNowak** [comment]
Jak rozumiem to mają być prezentacje z:
- #4
- #10 
- #5 
- I pewnie to jak idą postępy nad botem?

**Comment by TheJimmyNowak** [comment]
Dla wszystkich, którzy mają prezentację, możemy zrobić czas na prezentacje na następnym spotkaniu w czwartek ^^

@annbbbb @Sygnator @Pyra123 @Kleczyk
