### ISSUE TITLE
Dodanie polecenia !q -> wywołującego LLMa

### ISSUE THREAD

**Issue by finloop** [knmlprz/ChatKNML#39]
## Jaki jest cel tego tego zadania

Dodanie polecenia wywołującego zapytanie do LLMa.

## Jak wygląda rozwiązanie?

Po wpisaniu na discordzie `!q <Pytanie>`  Otrzymasz odpowiedź, podobną do tej, jaką generuje ChatGPT ;)

## TODO:

- [x] Dodanie komendy

Closed by #44

**Comment by TheJimmyNowak** [comment]
Do wyjebania
