### ISSUE TITLE
Stworzyć struktury danych pod dokumenty

### ISSUE THREAD

**Issue by TheJimmyNowak** [knmlprz/ChatKNML#46]
## Jaki jest cel tego tego zadania
Przygotowanie struktur danych dla parserów

## Jak wygląda rozwiązanie?
Napisanie modeli w django

## TODO:
- [ ] Zaproponować strukturę
- [ ] Implementacja modeli

**Comment by finloop** [comment]
Proponuję następującą strukturę danych (zainspirowaną llama-index), oczywiście trzeba ją przerobić na model Django.

```python
class Document:
  text: str
  embedding: list[float],
  source: url
  metadata: dict[str, Any]

class Chunk:
  text: str
  embedding: list[float],
  source_document: Document
```

`Document` - cały tekst ze strony internetowej, z wikipedii etc. Powinien być oczyszczony tj. zawierać tekst bez znaków specjalnych i np. 5 enterów z rzędu.
`Chunk` - fragment dokumentu ze strony internetowej.

**Comment by Kleczyk** [comment]
W "Document source" nie zawsze musi być URL, np dokument jest przygotowany przez nas, na przykład dialogi użytkowników (w przyszłości) lub własne teksty, ale możemy wtedy  dodawać  do metadata.

Byłoby fajnie przechowywać miejsce tego w Document  kolejność albo znak od do

```python
class Document:
  text: str
  embedding: list[float],
  source: str
  metadata: dict[str, Any]

class Chunk:
  text: str
  embedding: list[float],
  source_document: Document
  begin: int
  end: int
 
```

**Comment by finloop** [comment]
@Kleczyk 

> W "Document source" nie zawsze musi być URL, np dokument jest przygotowany przez nas, na przykład dialogi użytkowników (w przyszłości) lub własne teksty, ale możemy wtedy dodawać do metadata.

Ok, chyba źle to nazwałem. Generalnie chciałbym żeby ten dokument oznaczał pewien dokument z internetu. Pod:
- dokument przygotowany przez nas,
- przykład dialogi użytkowników

Przygotowałbym osobne tabele. Nie trzymajmy wszystkiego w jednej tabeli, bo musielibyśmy często korzystać np. z pola `metadata`. A jak zrobimy tak:

```python
class WebDocument:
  text: str
  embedding: list[float]
  source: url
```

Usunąłem pole metadata, bo jest zbyt ogólne — może być tam wrzucone wszystko i dorzuciłoby to sporo logiki w aplikacji. Jeżeli ktoś będzie chciał dodać jakieś pole, to po prostu je tu doda i zrobi migrację na bazie danych.

> Byłoby fajnie przechowywać miejsce tego w Document kolejność albo znak od do

Tak.  Dobry pomysł. Zmieniłbym nazwy tych pól na bardziej deskryptywne.

```python
class WebDocumentChunk:
  text: str
  embedding: list[float],
  source_document: WebDocument
  start_char_idx: int
  end_char_idx: int
```

**Comment by bisd98** [comment]
Chciałbym przegadać temat struktury danych na voicechacie, ponieważ mam kilka pytań, a nie chcę floodować wątku.

**Comment by finloop** [comment]
@bisd98 Napisz je, to będziemy mieli czas się przygotować.

**Comment by finloop** [comment]
> Jakie struktury dokumentów budują moduły, których używamy?

 LLamaindex i langchain używają jeszcze prostszej strukrury, która przypomina:
```python
class Document:
  text: str
  metadata: url
```
Więc każdy `WebDocument` da się przetworzyć na dokument dla tych frameworków (o ile będziemy z nich korzystać). 

> Jakie narzędzia bierzemy pod uwagę przy przeszukiwaniu dokumentów?

pgvector (simmilarity search, vector search) oraz pg_trgm (trigram matching, text search). Przedstawiona struktura pozwoli na korzystanie z tych funkcji.

> Czy narzędzia do przeszukiwania będą modyfikowalne do pracy z proponowaną strukturą?

Jakie narzędzia do przeszukiwania?

**Comment by finloop** [comment]
1. Używamy postgresa.
2. Napiszemy własny, prostszy (a właściwie to sql query). 

Generalnie to nie chcę uzywać gotowych rozwiązań, bo:
- 98% tamtych projektów nie wykorzsytamy
- frameworki te są anglo-centryczne, są testowane WYŁĄCZNIE na języku angielskim i dla niego najlepiej działają. 
- jakość kodu jest co najmniej średnia, patrz: tona abstrakcji wokół formatowania templates, a nawet nie jest otypowana

**Comment by bisd98** [comment]
Rozumiem to podejście i bardzo chętnie posłucham/poczytam o budowie tego rozwiązania. Kiedy będziemy mogli dowiedzieć się o nim więcej?

**Comment by finloop** [comment]
Co robi Parent Document Retriever:
- Dzieli dokument na chunki
- Robi vector search po chunkach
- Zwraca parent Document

Co my zrobimy:
- Podzielimy `WebDocument` na `WebDocumentChunk`
- Zrobimy vector search po `WebDocumentChunk` używając rozszerzenia pg_vector
- `WebDocumentChunk` zawiera referencje do `WebDocument` (czyli do rodzica)

**Comment by TheJimmyNowak** [comment]
> Przygotowałbym osobne tabele. Nie trzymajmy wszystkiego w jednej tabeli, bo musielibyśmy często korzystać np. z pola metadata. A jak zrobimy tak

Pomysł dobry, ale dokumenty niezależnie od typu będą też miały takie same pola 😉 Więc można zrobić tak.

```python
class Document(models.Model):
  text: str
  embedding: list[float],
  
class WebDocument(Document):
  source: url

# Przykładowa klasa
class Foo(Document):
  bar: str

```

I teraz nasuwa mi się kolejne pytanie, **czy chunki będą się pomiędzy sobą różniły?** Jeżeli nie to możemy zrobić jeden model chunk. Więc ostatecznie można by było zrobić coś takiego.

```python
class Chunk(models.Model):
  text: str
  embedding: list[float],
  chunk_idx: int
  start_char_idx: int
  end_char_idx: int

class Document(models.Model):
  text: str
  embedding: list[float],
  chunks: OneToMany Chunk
  
class WebDocument(Document):
  source: url

# Przykładowa klasa
class Foo(Document):
  bar: str

```

**Comment by TheJimmyNowak** [comment]
Btw @finloop co oznacza pole `chunk_idx`

**Comment by finloop** [comment]
Jak dzielisz dokument na chunki, to chunki te będą występowały w jakiejś kolejności. To pole mówi, który to chunk w dokumencie. Co ułatwi np. pobieranie poprzedniego chunka z dokumentu.

**Comment by bisd98** [comment]
Proszę o logikę pobierania poprzedniego chunka z dokumentu, bo mam wrażenie, że wchodzi tu pewna technika, o której nie rozmawialiśmy.

**Comment by TheJimmyNowak** [comment]
> Jak dzielisz dokument na chunki, to chunki te będą występowały w jakiejś kolejności. To pole mówi, który to chunk w dokumencie. Co ułatwi np. pobieranie poprzedniego chunka z dokumentu.

[django-ordered-model](https://github.com/django-ordered-model/django-ordered-model) Ta libka sprawę ułatwia. Możemy rozważyć użycie jej

**Comment by bisd98** [comment]
![Image](https://github.com/knmlprz/ChatKNML/assets/107929119/cc5474b4-e5fd-40ee-985d-316f9b4da46b)

**Comment by finloop** [comment]
Zamykamy? Jeżeli nie to zamykamy to jutro po południu.

**Comment by TheJimmyNowak** [comment]
@finloop 

> Zamykamy? Jeżeli nie to zamykamy to jutro po południu.

Polska język trudna język :p

Koledze chodziło o to:

Zamykamy? Jeśli nikt nie ma nic do dodania to jutro po południu zamykamy

**Comment by TheJimmyNowak** [comment]
Było milion razy temat zamykam

![image](https://github.com/knmlprz/ChatKNML/assets/32245772/02a58060-eb10-4fb9-a97e-ecdd9708ca38)
