### ISSUE TITLE
Implementacja modeli

### ISSUE THREAD

**Issue by TheJimmyNowak** [knmlprz/ChatKNML#68]
## Jaki jest cel tego tego zadania
Zaimplementowanie odpowiednich modeli do django tak abyśmy mogli zacząć pisać API!

## Jak wygląda rozwiązanie?
Zaimplementowanie modeli z #46 

## TODO:
- [ ] Implementacja modeli
- [ ] Migracje
- [ ] Django admin (nie wiem czy tak to działa w ninjy :p )

## Powiązane taski/bugi
#46
Blocked by #67

**Comment by finloop** [comment]
@TheJimmyNowak A nie lepiej połączyć to zadanie z CRUDem?

**Comment by finloop** [comment]
Bo osoba, która będzie klepała CRUDa prawdopodobnie będzie musiała czekać aż modele przejdą przez review etc. A tak zrobi to wszystko na raz i poprawi błędy w modelach (jeżeli jakieś będą).

**Comment by TheJimmyNowak** [comment]
Można ale napisałem to na łotpierdol, bo i tak będę chłopaka kopał. Siedzi właśnie obok mnie i to klepie, więc wyląduje to wszystko w jednym PR
