### ISSUE TITLE
Cleanup repo

### ISSUE THREAD

**Issue by finloop** [knmlprz/ChatKNML#73]
## Jaki jest cel tego tego zadania

Wyczyszczenie repo z niepotrzebnych plików, które pojawiły się tam po ostanich PR.

## Jak wygląda rozwiązanie?

Należy usunąć folder discord, oraz embedding API z docker-compose.yml

## TODO

- [ ] Usunąc folder discord
- [ ] Usunąć typo ze słownika

**Comment by finloop** [comment]
@TheJimmyNowak Przenieś do TODO jeżeli opis jest ok

**Comment by TheJimmyNowak** [comment]
Czemu usunąć embedding API z docker-compose? Jest przecież podzielone produkcję i deva

**Comment by finloop** [comment]
@TheJimmyNowak Bo to było zanim przed podzieleniem go na produkcję i deva ;) już poprawiłem
