### ISSUE TITLE
Github workflow Linting dla skryptów shellowych

### ISSUE THREAD

**Issue by finloop** [knmlprz/ChatKNML#76]
## Jaki jest cel tego tego zadania

Wykrywanie często popełnianych błędów w skryptach.

## Jak wygląda rozwiązanie?

Napisać github workflow, który sprawdzi skrypty.

## TODO

- [ ] Napisac workflow
- [ ] Poprawić obecne skrypty

## Przydatne linki

- https://github.com/marketplace/actions/shellcheck

**Comment by finloop** [comment]
@TheJimmyNowak Przenieś do TODO jeżeli opis jest ok

**Comment by pgronkievitz** [comment]
@pgronkievitz add link & close this
