### ISSUE TITLE
Obsługa staticów przez django

### ISSUE THREAD

**Issue by TheJimmyNowak** [knmlprz/ChatKNML#95]
## Jaki jest cel tego zadania
Obecnie po uruchomieniu `docker compose` pliki static nie ładują się. Dopiero po ponownym uruchomieniu `docker compose exec api python manage.py collectstatic` zaczynają działać. Celem tego taska jest skonfigurowanie dockera tak aby nie trzeba było za każdym uruchomieniem włączać collectstatic.

[Docsy django](https://docs.djangoproject.com/en/5.0/howto/static-files/)

**Comment by pgronkievitz** [comment]
Sugeruję użyć multistage builda i nginxa do tego, zamiast kisić wszystko w tym jednym

**Comment by Sygnator** [comment]
Zrobione czeka na review -  https://github.com/knmlprz/ChatKNML/pull/96
